### ISSUE TITLE
spring-security-jwt-redis-demo对应的问题

### ISSUE THREAD

**Issue by admlnos** [C3Stones/blog#10]
为什么在JWTConfig.java下提示未配置Spring boot配置注解处理器

**Comment by C3Stones** [comment]
在JWTConfig中通过@ConfigurationProperties将配置文件中的属性注入到bean的属性中。
Spring Boot使用注释处理器在元数据文件（META-INF/Spring autoconfigure metadata.properties）中收集自动配置的条件。如果存在该文件，它将迫切地过滤不匹配的配置，这将缩短启动时间。建议在包含自动配置的模块中添加以下依赖项：
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-autoconfigure-processor</artifactId>
	<optional>true</optional>
</dependency>
```
